[ls-gui-cvn] Add lsstat skeleton, a stat() wrapper
After much frustration, it finally compiles. But, currently gives:

  Error: LsStat ctor: syscall stat() failed: Bad address

I suspect I'd need to initialize my smartpointer somehow. ...